<?php /** @var Toptal\Blog\Block\Posts $block */ ?>
<h1>Toptal Posts</h1>
<?php foreach($block->getPosts() as $post): ?>
    <?php /** @var Toptal\Blog\Model\Post */ ?>
    <h2><a href="<?php echo $block->getPostUrl($post);?>"><?php echo $post->getTitle(); ?></a></h2>
    <p><?php echo $post->getContent(); ?></p>
<?php endforeach; ?>
<br />
<br />
<h1>Create New Blog</h1>
<form action="<?php echo $this->getUrl("blog/post/submit")?>" method="post">
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="input" name="title" id="title">
        <textarea name="content" rows="10" cols="30">Enter your blog content</textarea>
        <button type="submit" class="btn btn-default">Submit</button>
    </div>
</form>