<!--Ajax Will update this section -->
<div id="ajaxData">
    <?php /** @var Kvr\Blog\Block\Posts $block */ ?>
    <h1>Kvr Posts</h1>
    <p class="ajaxData">
        <?php foreach($block->getPosts() as $post): ?>
            <?php /** @var Kvr\Blog\Model\Post */ ?>
            <div>
                <span>Title:<strong> <a href="<?php echo $block->getPostUrl($post);?>"><?php echo $post->getTitle(); ?></a></strong></span>
                <span>Content: <?php echo $post->getContent(); ?></span>
                <span>PostID: <?php echo $post->getId(); ?></span>
                <span>Date: <?php echo $post->getCreatedAt(); ?></span>
            </div>
        <?php endforeach; ?>
    </p>
</div>

<br />
<br />
<h1>Create New Blog</h1>
<form id="blogPost" method="post">
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="input" name="title" id="title">
        <textarea name="content" rows="10" cols="30">Enter your blog content</textarea>
        <button id="blogSubmit" type="submit" class="btn btn-default">Submit</button>
    </div>
</form>
<div class="loading">
    <img alt="loading" src="<?php //Pub Static path of module - static/version1528692354/frontend/../en_US/Kvr_Blog/images/loading.gif
    //Need to run static content cmd
    //echo $block->getViewFileUrl('Kvr_Blog::images/loading.gif');
   echo $block->getUrl('pub/media/kvr/').'loading.gif'; ?>" />

</div>
<script>
    var baseUrl = "<?php echo $block->getUrl('blog/') ?>";
</script>