<!--Ajax Will update this section -->
<div id="ajaxData">
    <?php /** @var Kvr\Blog\Block\Posts $block */ ?>
    <h1>Kvr Posts</h1>
    <p class="ajaxData">
        <?php foreach($block->getPosts() as $post): ?>
            <?php /** @var Kvr\Blog\Model\Post */ ?>
            <div>
                <span>Title:<strong> <a href="<?php echo $block->getPostUrl($post);?>"><?php echo $post->getTitle(); ?></a></strong></span>
                <span>Content: <?php echo $post->getContent(); ?></span>
                <span>PostID: <?php echo $post->getId(); ?></span>
                <span>Date: <?php echo $post->getCreatedAt(); ?></span>
            </div>
        <?php endforeach; ?>
    </p>
</div>

<br />
<br />
<h1>Create New Blog</h1>
<form id="blogPost" method="post">
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="input" name="title" id="title">
        <textarea name="content" rows="10" cols="30">Enter your blog content</textarea>
        <button id="blogSubmit" type="submit" class="btn btn-default">Submit</button>
    </div>
</form>

<script>
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $('#blogSubmit').click(function(e) {
                e.preventDefault();
                var customurl = "<?php echo $block->getUrl('blog/post/submit') ?>";

                $.ajax({
                    type: 'POST',
                    url: customurl,
                    data: $('#blogPost').serialize(),
                    beforeSend:function()
                    {
                        $('.loader').show();
                    },
                    success: function (msg) {
                        console.log(JSON.stringify(msg));
                        $( "#ajaxData" ).load( "https://demotujar.stagingbuilds.com/blog/index/index #ajaxData" );
                    }
                });
            });
        });
    });
</script>