<?php /** @var Kvr\Blog\Block\View $block */ ?>
<h1>Update your Blog</h1>
<form id="blogPost" method="post">
    <div class="form-group">
        <label for="postid">Post Id:</label>
        <input type="text" class="input" name="postid" id="postid" value="<?php echo $block->getPos()->getId(); ?>" readonly>
        <label for="title">Title:</label>
        <input type="text" class="input" name="title" id="title" value="<?php echo $block->getPos()->getTitle(); ?>">

        <textarea name="content" rows="10" cols="30"><?php echo $block->getPos()->getContent(); ?></textarea>
        <label for="date">Date:</label>
        <input type="text" class="input" name="date" id="date" value="<?php echo $block->getPos()->getCreatedAt();?>" readonly>

        <button id="blogSubmit" type="submit" class="btn btn-default Update">Update</button>
    </div>
</form>
<div class="loading">
    <img alt="loading" src="<?php //Pub Static path of module - static/version1528692354/frontend/../en_US/Kvr_Blog/images/loading.gif
    //Need to run static content cmd
    //echo $block->getViewFileUrl('Kvr_Blog::images/loading.gif');
    echo $block->getUrl('pub/media/kvr/').'loading.gif'; ?>" />

</div>
<script>
    var baseUrl = "<?php echo $block->getUrl('blog/post/view') ?>";
</script>