<?php /** @var Kvr\Blog\Block\View $block */ ?>
<h1><?php echo $block->getPos()->getTitle(); ?></h1>
<p>Update your Blog</p>
<form id="blogPost" method="post">
    <div class="form-group">
        <label for="postid">Post Id:</label>
        <input type="text" class="input" name="postid" id="postid" value="<?php echo $block->getPos()->getId(); ?>" readonly>
        <label for="title">Title:</label>
        <input type="text" class="input" name="title" id="title" value="<?php echo $block->getPos()->getTitle(); ?>">

        <textarea name="content" rows="10" cols="30"><?php echo $block->getPos()->getContent(); ?></textarea>
        <label for="date">Date:</label>
        <input type="text" class="input" name="date" id="date" value="<?php echo $block->getPos()->getCreatedAt();?>" readonly>

        <button id="blogSubmit" type="submit" class="btn btn-default">Submit</button>
    </div>
</form>